
import { CONSTANTS } from './constants';

export let CONFIG = {
    
    ALLOW_POSTMESSAGE_POPUP: false,

    LOG_LEVEL: 'info',

    ACK_TIMEOUT: 500,

    LOG_TO_PAGE: false,
    
    MOCK_MODE: false,

    ALLOWED_POST_MESSAGE_METHODS: {
        [ CONSTANTS.SEND_STRATEGIES.POST_MESSAGE ]: true,
        [ CONSTANTS.SEND_STRATEGIES.POST_MESSAGE_GLOBAL_METHOD ]: true,
        [ CONSTANTS.SEND_STRATEGIES.POST_MESSAGE_UP_THROUGH_BRIDGE ]: true,
        [ CONSTANTS.SEND_STRATEGIES.POST_MESSAGE_DOWN_THROUGH_BRIDGE ]: true
    }
};